"""
Outputs MAS (Multi-Agent System) Pipeline.

Orchestrates the generation of complex markdown documents (Reports, Tables, Scripts)
via a Researcher -> Writer -> Reviewer workflow.
"""

from __future__ import annotations

import logging
import re
from datetime import datetime
from pathlib import Path

from llama_index.core.llms import ChatMessage, MessageRole

from indexnote.config import Settings, create_llm
from indexnote.retrieval.query_engine import QueryEngine

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------

WRITER_PROMPTS = {
    "report": """You are the **Writer Agent**. Your task is to draft a comprehensive, formal **Report** on the requested topic using ONLY the provided research context.

FORMATTING RULES:
1. You MUST use endnote style with in-text citations (e.g., [1], [2]) whenever you state a fact.
2. Structure the report with a clear Title (using a single # heading), an Introduction, well-organized body paragraphs with subheadings (## or ###), and a Conclusion.
3. At the very bottom, include a "## References" section where you list the sources using their numbers. Example: "[1] source_file.md"
4. NEVER hallucinate information. If the context does not contain the answer, you may make a logical conjecture and present it as a conjecture, but you MUST clearly label it as a conjecture.
""",

    "table": """You are the **Writer Agent**. Your task is to draft a comprehensive **Data Table** comparing and contrasting the requested topic using ONLY the provided research context.

FORMATTING RULES:
1. Output MUST be primarily a Markdown table.
2. Choose highly meaningful columns (e.g., Feature, Concept A, Concept B, Key Differences) based on the context.
3. You may include a brief introductory paragraph before the table and a brief summary after it.
4. Include inline citations (e.g., [Source 1]) inside the table cells where appropriate.
5. NEVER hallucinate information. If the context lacks data, write "N/A" or "Not specified".
""",

    "script": """You are the **Writer Agent**. Your task is to draft an engaging **Script** (e.g., a 2-person podcast or single-speaker lecture) on the requested topic using ONLY the provided research context.

FORMATTING RULES:
1. The script MUST read naturally, like spoken dialogue.
2. DO NOT use bracketed numbers like [Source 1] for citations. Instead, you MUST refer to sources conversationally by their human-readable Titles (e.g., "According to the Foundations of Physiology notes..."). 
3. Use character names (e.g., HOST: ..., EXPERT: ...) if writing a dialogue.
4. Make the tone engaging, informative, and easy to follow orally.
5. Do not output formatted mathematical equations(LaTeX, Unicode, etc), translate equations from context into clear and concise spoken english using words not mathematical symbols.
6. NEVER hallucinate information. Stick strictly to the facts provided in the context.
"""
}

REVIEWER_PROMPT = """You are the **Reviewer and Fact-Checker Agent**.
You will be provided with the Original Research Context and the Draft generated by the Writer.

YOUR TASKS:
1. **Fact-Checking**: Ensure every claim in the draft is strictly supported by the Original Research Context. Remove or correct any falsehoods.
2. **Formatting**: Ensure the draft strictly follows the requested Output Type formatting:
   - If it's a 'report', ensure in-text citations are written as endnotes [1] and are present, and a References section exists at the bottom.
   - If it's a 'table', ensure the markdown table is correctly formatted and accurate.
   - If it's a 'script', ensure citations are spoken naturally by title, NOT by bracketed numbers.
3. **Refinement**: Fix any grammatical errors, improve flow, and output the absolute FINAL markdown document.
4. **No Mathematical Formatting**: DO NOT output formatted mathematical equations (LaTeX, Unicode, etc). Translate any equations from the context into clear, concise conversational English using standard words.

Output ONLY the final markdown content. Do not include introductory remarks like "Here is the revised draft" or wrap the entire thing in a markdown code block unless the entire file is meant to be a code block (it isn't, just output raw markdown text).
"""


class MASPipeline:
    """Orchestrates the Researcher -> Writer -> Reviewer workflow."""

    def __init__(self, query_engine: QueryEngine, settings: Settings):
        self._query_engine = query_engine
        self._llm = create_llm(settings)
        self._output_dir = Path("outputs")
        self._output_dir.mkdir(parents=True, exist_ok=True)

    def generate_output(self, output_type: str, topic: str) -> str:
        """
        Run the MAS pipeline to generate the requested output type.

        Args:
            output_type: "report", "table", or "script".
            topic: The user's requested topic.

        Returns:
            The path to the generated markdown file.
        """
        output_type = output_type.lower()
        if output_type not in WRITER_PROMPTS:
            raise ValueError(f"Unknown output type: {output_type}. Must be 'report', 'table', or 'script'.")

        logger.info("[MAS Researcher] Gathering context for topic: %s", topic)
        
        # 1. RESEARCHER: Gather context
        context_str, citations = self._query_engine.get_context(topic)
        
        if not context_str:
            raise ValueError("No relevant context found in the knowledge base to generate an output.")

        # Build a citation mapping string for the prompt
        citation_mapping = "Available Sources:\n"
        for c in citations:
            citation_mapping += f"[Source {c.index}] Title: {c.file_name} (Path: {c.file_path})\n"

        # 2. WRITER: Draft the document
        logger.info("[MAS Writer] Drafting %s...", output_type)
        writer_system_prompt = WRITER_PROMPTS[output_type]
        
        writer_messages = [
            ChatMessage(role=MessageRole.SYSTEM, content=writer_system_prompt),
            ChatMessage(role=MessageRole.USER, content=f"TOPIC: {topic}\n\n{citation_mapping}\n\nORIGINAL RESEARCH CONTEXT:\n{context_str}\n\nPlease draft the document now.")
        ]
        
        draft_response = self._llm.chat(writer_messages)
        draft_text = draft_response.message.content

        # 3. REVIEWER: Fact-check and finalize
        logger.info("[MAS Reviewer] Fact-checking and refining draft...")
        
        reviewer_messages = [
            ChatMessage(role=MessageRole.SYSTEM, content=REVIEWER_PROMPT),
            ChatMessage(role=MessageRole.USER, content=(
                f"OUTPUT TYPE REQUESTED: {output_type}\n\n"
                f"TOPIC: {topic}\n\n"
                f"{citation_mapping}\n\n"
                f"ORIGINAL RESEARCH CONTEXT:\n{context_str}\n\n"
                f"WRITER DRAFT TO REVIEW:\n{draft_text}\n\n"
                f"Please provide the final, perfected markdown document."
            ))
        ]
        
        final_response = self._llm.chat(reviewer_messages)
        final_text = final_response.message.content.strip()
        
        # Clean up stray markdown code block wrappers from the LLM response if present
        if final_text.startswith("```markdown"):
            final_text = final_text[11:]
        elif final_text.startswith("```"):
            final_text = final_text[3:]
        if final_text.endswith("```"):
            final_text = final_text[:-3]
        final_text = final_text.strip()

        # 4. Save to file
        slug = re.sub(r'[^a-zA-Z0-9]+', '-', topic)[:50].strip('-').lower()
        if not slug:
            slug = "output"
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{slug}_{output_type}_{timestamp}.md"
        filepath = self._output_dir / filename
        
        filepath.write_text(final_text, encoding="utf-8")
        logger.info("[MAS Pipeline] Final output saved to %s", filepath)
        
        return str(filepath)
